apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node
  labels:
    app: simple-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-node
        image: thismycatsdockerhub/simple-node
        ports:
