version: "3"
services:
    reverseproxy:
        image: thismycatsdockerhub/reverseproxy
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - api-user
            - api-feed  
    api-user:
        build: 
            context: udagram-api-user
        environment:
            POSTGRESS_USERNAME: $POSTGRESS_USERNAME
            POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
            POSTGRESS_DB: $POSTGRESS_DB 
            POSTGRESS_HOST: $POSTGRESS_HOST 
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_BUCKET: $AWS_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"
    api-feed:
        build:
            context: udagram-api-feed 
        environment:
            POSTGRESS_USERNAME: $POSTGRESS_USERNAME
            POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
            POSTGRESS_DB: $POSTGRESS_DB 
            POSTGRESS_HOST: $POSTGRESS_HOST 
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_BUCKET: $AWS_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"
    frontend:
        build: ./udagram-frontend
   
        